name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    name: Validate Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate PR commits
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.3.2

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --format compact

  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: "1.9.0"
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Test
        run: terraform test
